### ISSUE TITLE
Not sure how to create user for my database and create a new user in Paypal using Oauth

### ISSUE THREAD

**Issue by NyaYean** [NyaYean/Sharement#1]
@DrRobotmck @harimohanraj89 @WilliamfShaw @bigtone1284 @h4w5 

Hey,

I am having an issue wrapping my head around creating a user into my database and PayPal simultaneously. I can already create users into my database but I'm not sure how to create a PayPal user at the same time. Please assist. Thanks

**Comment by DrRobotmck** [comment]
Can you make paypal accounts through their api?

**Comment by NyaYean** [comment]
Yes you can make accounts through the api. This is want to do initially but
I was told by classmates that I would need oath

**Comment by DrRobotmck** [comment]
Can you direct me to their documentation for creating a user account through their api?

**Comment by NyaYean** [comment]
Sure, its
https://developer.paypal.com/docs/classic/adaptive-accounts/gs_AdaptiveAccounts/

On Fri, May 8, 2015 at 3:05 PM, McKenneth Scott III <
notifications@github.com> wrote:

> Can you direct me to their documentation for creating a user account
> through their api?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Nyeanafehn/Sharement/issues/1#issuecomment-100329875.

## 

-Nya Yeanafehn

**Comment by NyaYean** [comment]
Still not too sure as to implement Oauth into my app. I've downloaded a few gems for PayPal, but I'm not too sure as what to do next. Please assist. Thanks

**Comment by harimohanraj89** [comment]
Which gem are you currently using to try to solve this problem?

**Comment by NyaYean** [comment]
I'm using paypal-sdk-rest and paypal-sdk-adaptiveaccounts.

On Mon, May 11, 2015 at 2:38 PM, Hari Mohanraj notifications@github.com
wrote:

> Which gem are you currently using to try to solve this problem?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Nyeanafehn/Sharement/issues/1#issuecomment-101012326.

## 

-Nya Yeanafehn

**Comment by harimohanraj89** [comment]
Cool. It seems like you're using `paypal-sdk-rest` to allow users to log in to your application through their PayPal account. Also, it seems like you're using `paypal-sdk-adaptiveaccounts` to allow users to **also** create PayPal accounts through your application. These are two separate problems, and it may be best to focus on them one at a time.

The first step would be to allow users to log in to your application through **existing** PayPal accounts, using the `paypal-sdk-rest` gem. Have you been able to achieve this functionality? Are you following the instructions listed on the [GitHub page](https://github.com/paypal/PayPal-Ruby-SDK)? If so, on what step are you running into a problem? What problem are you running into?

**Comment by NyaYean** [comment]
I did not know that was the difference between the two. The problem I'm
running to is that I do not know how to really test it out to see if works.
I am following the directions and I am unsure where to put what from the
examples on the GitHub page. This is my problem so far.

On Mon, May 11, 2015 at 3:00 PM, Hari Mohanraj notifications@github.com
wrote:

> Cool. It seems like you're using paypal-sdk-rest to allow users to log in
> to your application through their PayPal account. Also, it seems like
> you're using paypal-sdk-adaptiveaccounts to allow users to _also_ create
> PayPal accounts through your application. These are two separate problems,
> and it may be best to focus on them one at a time.
> 
> The first step would be to allow users to log in to your application
> through _existing_ PayPal accounts, using the paypal-sdk-rest gem. Have
> you been able to achieve this functionality? Are you following the
> instructions listed on the GitHub page
> https://github.com/paypal/PayPal-Ruby-SDK? If so, on what step are you
> running into a problem? What problem are you running into?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Nyeanafehn/Sharement/issues/1#issuecomment-101017575.

## 

-Nya Yeanafehn

**Comment by harimohanraj89** [comment]
Ok. I'm going to do some research. It may be a good idea to context switch and work on another facet of your application that requires your attention.

**Comment by NyaYean** [comment]
Will do, thanks!

On Mon, May 11, 2015 at 3:27 PM, Hari Mohanraj notifications@github.com
wrote:

> Ok. I'm going to do some research. It may be a good idea to context switch
> and work on another facet of your application that requires your attention.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Nyeanafehn/Sharement/issues/1#issuecomment-101024692.

## 

-Nya Yeanafehn
