### ISSUE TITLE
Issues with creating a new path for agreements for my app

### ISSUE THREAD

**Issue by NyaYean** [NyaYean/Sharement#5]
@harimohanraj89 @bigtone1284 @DrRobotmck @WilliamfShaw 

Good Morning,

I am having issues with creating a new path for creating new agreements for my app. I've already have routes, controllers, and views for agreements. I also have a link that is in on the users page for creating new agreements but when I click on it, it creates a new agreements but it does not take me to new view for agreements. 

Please assist, if you have any questions, please feel free to contact me. Thanks.

**Comment by harimohanraj89** [comment]
Please follow the format for asking questions, so we have enough information to help you effectively.

**Comment by NyaYean** [comment]
The user story I am currently working on is, "As a user, I want to create agreements to my accounts so that users can contribute to a common cause". I am trying to create a page that will allow users to create an agreement. The issue at hand is that I have a link that connect me to the AgreementController and the "new" method. When I click the link, this is what I get 
![screen shot 2015-05-12 at 12 05 57 pm](https://cloud.githubusercontent.com/assets/9602712/7592064/631570f2-f89f-11e4-9bf7-b8cdc9ece22a.png)

I've so far referred to the homework solution from two weeks ago in regards to views for playlists and songs. I've also used rails console to see if you I can create a new agreement and it is possible. I've also spoken to a few of my classmates about it and they've pointed to me that this section of my code..
![screen shot 2015-05-12 at 12 10 45 pm](https://cloud.githubusercontent.com/assets/9602712/7592188/f46b10ac-f89f-11e4-919b-12f60fb1b367.png) might the problem. I'm too sure what to do int this situation at this moment

**Comment by WilliamfShaw** [comment]
@Nyeanafehn The answer is in the error, your page is trying to render html for a view you havent created

**Comment by NyaYean** [comment]
![screen shot 2015-05-12 at 1 06 59 pm](https://cloud.githubusercontent.com/assets/9602712/7593454/488f5960-f8a8-11e4-9a23-2b349d8a4a66.png)
I have a new.html.erb view that's already created. Maybe it's the syntax?

**Comment by WilliamfShaw** [comment]
@Nyeanafehn take a look at how the agreements folder is spelled

**Comment by WilliamfShaw** [comment]
@Nyeanafehn Also I am going to close this because that is your issue

**Comment by NyaYean** [comment]
Haha..thanks
