### ISSUE TITLE
Having issues with associating agreements to the user that created it

### ISSUE THREAD

**Issue by NyaYean** [NyaYean/Sharement#6]
@harimohanraj89 @DrRobotmck @WilliamfShaw @bigtone1284 

Good Afternoon,

I am issues with associating created agreements to the user that created it. I am on the user story, "As a user, I want to create agreements to my accounts so that users can contribute to a common cause". In this part of the user story, I can create agreements and save them on the database. 

When I check psql and check out the join table, I see that agreements and users are saved but nothing is saved to the join table as listed below..

![screen shot 2015-05-12 at 4 19 34 pm](https://cloud.githubusercontent.com/assets/9602712/7597608/be887092-f8c2-11e4-89b8-c7e034e8aa82.png)

I tried going through all of the examples listed in the solution for the tunr_app but I cannot find an example that shows how to explicitly do it. I searching online and I still not wrapping my head on how to do it.

This is the code I have so far in my AgreementsController

![screen shot 2015-05-12 at 4 23 21 pm](https://cloud.githubusercontent.com/assets/9602712/7597715/4e1b96ee-f8c3-11e4-8716-8c6fd1763667.png)

Please assist. Thanks

**Comment by harimohanraj89** [comment]
Your agreements controller so far only has code to create agreements. If you want to add users to agreements (create entries in that join table), you will need to explicitly write the code to do so. If the associations in your user and agreement models are set up correctly, then you will have to write code, probably your `agreements#create` action, that looks like this:

``` rb
@agreement.users.push(current_user)
```

This is the line of code that adds an entry to the join table.
